Santor\MainBundle\Entity\Comment:
    type: entity
    table: Comment
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        age:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        mail:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        message:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
