Santor\MainBundle\Entity\Role:
    type: entity
    table: Role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
